version: '3.8'

services:
  identityaccess_mysql:
    image: mysql:8.0
    container_name: identityaccess_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"
  
  taskmanage_mysql:
    image: mysql:8.0
    container_name: taskmanage_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db_taskmanage
      MYSQL_USER: user2
      MYSQL_PASSWORD: password2
    volumes:
      - dbdata_taskmanage:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3308:3306"
      
  identityacces_nextjs:
    image: node:18
    container_name: identityaccess_frontend
    working_dir: /var/www/identityaccess_frontend
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./identityaccess_frontend:/var/www/identityaccess_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
  
  taskmanage_nextjs:
    image: node:18
    container_name: taskmanage_frontend
    working_dir: /var/www/taskmanagement_frontend
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./taskmanagement_frontend:/var/www/taskmanagement_frontend
    ports:
      - "3001:3000"
    networks:
      - app-network

  identity:
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/identityAccess/src/public
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_DOCUMENT_ROOT: /var/www/html/identityAccess/src/public
    container_name: identity
    volumes:
      - ./identityAccess:/var/www/html/identityAccess
    ports:
      - "8080:80"
    networks:
      - app-network

  task:
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/taskManagement/src/public
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_DOCUMENT_ROOT: /var/www/html/taskManagement/src/public
    container_name: task
    volumes:
      - ./taskManagement:/var/www/html/taskManagement
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  dbdata_taskmanage:
    driver: local