version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"
      
  nextjs:
    image: node:18
    container_name: identityaccess_frontend
    working_dir: /var/www/identityaccess_frontend
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./identityaccess_frontend:/var/www/identityaccess_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache
    volumes:
      - ./identityAccess:/var/www/html/identityAccess
      - ./taskManagement:/var/www/html/taskManagement
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local